language: python
python:
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy3"
install:
  - pip install asynctest
script:
  - python -m unittest
jobs:
  include:
    - stage: code check
      name: flake8
      python: 3.6
      install: pip install -q flake8
      script: flake8 .
    - stage: code check
      name: isort
      python: 3.6
      install: pip install -q isort
      script: isort --check-only --recursive .
matrix:
  allow_failures:
    - python: pypy3
